# Generated by Django 4.2.3 on 2023-07-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_studentpresence_student_studentpresence_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpresence',
            name='user',
        ),
    ]
