# Generated by Django 4.2.3 on 2023-07-16 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0011_remove_teacher_matricule'),
        ('api', '0004_remove_studentpresence_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpresence',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='absences.student'),
            preserve_default=False,
        ),
    ]
