# Generated by Django 4.2.3 on 2023-07-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=300, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
