# Generated by Django 4.2.3 on 2023-07-15 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='token',
            field=models.CharField(default='token', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TeacherModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absences.module')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absences.teacher')),
            ],
        ),
    ]
