# Generated by Django 4.2.3 on 2023-07-15 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0006_teachermodule_group_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absences.timetable')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absences.student')),
            ],
        ),
    ]
