# Generated by Django 4.2.3 on 2023-07-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0007_absence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='token',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='active',
        ),
    ]
