# Generated by Django 4.2.3 on 2023-07-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0008_remove_student_token_remove_teacher_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='token',
        ),
        migrations.AddField(
            model_name='teacher',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
