# Generated by Django 4.2.3 on 2023-07-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0010_student_user_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='matricule',
        ),
    ]
